"""ICAO Doc 9303 nationality / issuing-state codes (ISO 3166-1 alpha-3 plus ICAO specials)."""
from __future__ import annotations

ISO_ALPHA3 = set("""
ABW AFG AGO AIA ALA ALB AND ARE ARG ARM ASM ATA ATF ATG AUS AUT AZE BDI BEL BEN BES BFA BGD BGR BHR BHS BIH BLM BLR
BLZ BMU BOL BRA BRB BRN BTN BVT BWA CAF CAN CCK CHE CHL CHN CIV CMR COD COG COK COL COM CPV CRI CUB CUW CXR CYM CYP
CZE DEU DJI DMA DNK DOM DZA ECU EGY ERI ESH ESP EST ETH FIN FJI FLK FRA FRO FSM GAB GBR GEO GGY GHA GIB GIN GLP GMB
GNB GNQ GRC GRD GRL GTM GUF GUM GUY HKG HMD HND HRV HTI HUN IDN IMN IND IOT IRL IRN IRQ ISL ISR ITA JAM JEY JOR JPN
KAZ KEN KGZ KHM KIR KNA KOR KWT LAO LBN LBR LBY LCA LIE LKA LSO LTU LUX LVA MAC MAF MAR MCO MDA MDG MDV MEX MHL MKD
MLI MLT MMR MNE MNG MNP MOZ MRT MSR MTQ MUS MWI MYS MYT NAM NCL NER NFK NGA NIC NIU NLD NOR NPL NRU NZL OMN PAK PAN
PCN PER PHL PLW PNG POL PRI PRK PRT PRY PSE PYF QAT REU ROU RUS RWA SAU SDN SEN SGP SGS SHN SJM SLB SLE SLV SMR SOM
SPM SRB SSD STP SUR SVK SVN SWE SWZ SXM SYC SYR TCA TCD TGO THA TJK TKL TKM TLS TON TTO TUN TUR TUV TWN TZA UGA UKR
UMI URY USA UZB VAT VCT VEN VGB VIR VNM VUT WLF WSM YEM ZAF ZMB ZWE
""".split())

ICAO_SPECIAL = {
    'D': 'GERMANY (D<<)', 'GBD': 'BRITISH OVERSEAS TERRITORIES CITIZEN', 'GBN': 'BRITISH NATIONAL (OVERSEAS)',
    'GBO': 'BRITISH OVERSEAS CITIZEN', 'GBP': 'BRITISH PROTECTED PERSON', 'GBS': 'BRITISH SUBJECT', 'EUE': 'EUROPEAN UNION',
    'UNO': 'UNITED NATIONS ORGANIZATION', 'UNA': 'UNITED NATIONS SPECIALIZED AGENCY', 'UNK': 'UNMIK KOSOVO', 'RKS': 'KOSOVO',
    'XBA': 'AFRICAN DEVELOPMENT BANK', 'XIM': 'AFRICAN EXPORT-IMPORT BANK', 'XCC': 'CARIBBEAN COMMUNITY', 'XCE': 'COUNCIL OF EUROPE',
    'XCO': 'COMMON MARKET FOR EASTERN AND SOUTHERN AFRICA', 'XEC': 'ECONOMIC COMMUNITY OF WEST AFRICAN STATES',
    'XES': 'ORGANIZATION OF EASTERN CARIBBEAN STATES', 'XMP': 'INTERNATIONAL COMMITTEE OF THE RED CROSS',
    'XOM': 'SOVEREIGN MILITARY ORDER OF MALTA', 'XPO': 'INTERPOL', 'XXA': 'STATELESS PERSON', 'XXB': 'REFUGEE (1951 CONVENTION)',
    'XXC': 'REFUGEE (OTHER)', 'XXX': 'UNSPECIFIED NATIONALITY', 'UTO': 'UTOPIA (ICAO SPECIMEN STATE)',
}

VALID_CODES = ISO_ALPHA3 | set(ICAO_SPECIAL)

# Printed demonyms / country names seen in visual zones -> code.
DEMONYMS = {
    'INDIAN': 'IND', 'INDIA': 'IND', 'NEPALESE': 'NPL', 'NEPALI': 'NPL', 'NEPAL': 'NPL', 'BANGLADESHI': 'BGD',
    'BANGLADESH': 'BGD', 'SRI LANKAN': 'LKA', 'SRI LANKA': 'LKA', 'BHUTANESE': 'BTN', 'BHUTAN': 'BTN', 'PAKISTANI': 'PAK',
    'PAKISTAN': 'PAK', 'AFGHAN': 'AFG', 'MYANMAR': 'MMR', 'BURMESE': 'MMR', 'CHINESE': 'CHN', 'CHINA': 'CHN',
    'AMERICAN': 'USA', 'UNITED STATES OF AMERICA': 'USA', 'BRITISH': 'GBR', 'BRITISH CITIZEN': 'GBR', 'UNITED KINGDOM': 'GBR',
    'GERMAN': 'DEU', 'DEUTSCH': 'DEU', 'GERMANY': 'DEU', 'FRENCH': 'FRA', 'FRANCAISE': 'FRA', 'FRANCE': 'FRA',
    'JAPANESE': 'JPN', 'JAPAN': 'JPN', 'RUSSIAN': 'RUS', 'RUSSIAN FEDERATION': 'RUS', 'AUSTRALIAN': 'AUS',
    'CANADIAN': 'CAN', 'BRAZILIAN': 'BRA', 'NIGERIAN': 'NGA', 'EMIRATI': 'ARE', 'SINGAPOREAN': 'SGP', 'UTOPIAN': 'UTO',
    'UTOPIA': 'UTO', 'STATELESS': 'XXA', 'ITALIAN': 'ITA', 'SPANISH': 'ESP', 'DUTCH': 'NLD', 'SWEDISH': 'SWE',
    'KOREAN': 'KOR', 'THAI': 'THA', 'MALAYSIAN': 'MYS', 'INDONESIAN': 'IDN', 'FILIPINO': 'PHL', 'VIETNAMESE': 'VNM',
    'SAUDI': 'SAU', 'IRANIAN': 'IRN', 'IRAQI': 'IRQ', 'TURKISH': 'TUR', 'EGYPTIAN': 'EGY', 'KENYAN': 'KEN',
    'SOUTH AFRICAN': 'ZAF', 'MEXICAN': 'MEX', 'ARGENTINE': 'ARG', 'UKRAINIAN': 'UKR', 'POLISH': 'POL',
}


def is_valid_code(code: str) -> bool:
    code = (code or '').replace('<', '').upper()
    return code in VALID_CODES


def to_code(text: str) -> str | None:
    """Map printed nationality text or a code to an ICAO code."""
    t = ' '.join((text or '').upper().replace('<', ' ').split())
    if not t:
        return None
    if t in VALID_CODES:
        return t
    if t in DEMONYMS:
        return DEMONYMS[t]
    from rapidfuzz import process, fuzz
    hit = process.extractOne(t, list(DEMONYMS), scorer=fuzz.ratio, score_cutoff=85)
    return DEMONYMS[hit[0]] if hit else None
